spring:
  application:
    name: mingapi-interface
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mingapi
    username: root
    password: 775821
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8123
  servlet:
    context-path: /api
mingapi-client:
  access-key: ming
  secret-key: 11111111

